version: '3.8'
services:
  rubiboard-frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./build:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default
   
